name: update readme content

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: npm run test

  update:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: npm run generate

  publish:
    needs: update
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git diff --staged --quiet README.md || git commit -m 'chore: update readme content' -m '[skip ci]'
          git push origin main --quiet
