name: update readme content

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

env:
  NODE_VERSION: "18.14.1"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: npm run generate
      - uses: actions/upload-artifact@v3
        with:
          name: readme
          path: README.md

  update:
    needs: generate
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: readme
      - name: commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git diff --staged --quiet README.md || git commit -m 'chore: update readme content' -m '[skip ci]'
          git push --quiet
